// 节点配图注册表 · 图片在 public/media/，均来自 Wikimedia Commons（公有领域或 CC 授权）
// credit 注明作者与许可；由 grok-agent skill 的 download-commons.cjs 生成
window.CODE_MEDIA = {
  "variable-assign": { file: "media/variable-assign.jpg", title: "磁芯存储器 · 早期「变量」的物理载体", credit: "José Luis Briz Velasco · Wikimedia Commons · CC BY-SA 4.0" },
  "data-types": { file: "media/data-types.jpg", title: "霍尔瑞斯穿孔卡 · 不同字段即不同类型的数据", credit: "Herman Hollerith · Wikimedia Commons · Public domain" },
  "io-basic": { file: "media/io-basic.jpg", title: "计算机键盘 · 输入输出的日常接口", credit: "Joe lope · Wikimedia Commons · CC BY-SA 4.0" },
  "string": { file: "media/string.jpg", title: "提花机穿孔卡 · 最早的「字符串/程序」载体", credit: "User Ghw on en.wikipedia · Wikimedia Commons · Public domain" },
  "error-types": { file: "media/error-types.jpg", title: "第一只「计算机虫」· 1945 年哈佛 Mark II 日志", credit: "Courtesy of the Naval Surface Warfare Center, Dahlgren, VA., · Wikimedia Commons · Public domain" },
  "boolean-cond": { file: "media/boolean-cond.jpg", title: "乔治·布尔像 · 布尔逻辑奠基人", credit: "Haks · Wikimedia Commons · Public domain" },
  "if-else": { file: "media/if-else.jpg", title: "流程图 · 分支决策的经典表达", credit: "Random1213123312 · Wikimedia Commons · CC0" },
  "list": { file: "media/list.jpg", title: "穿孔卡程序叠 · 有序序列的早期形态", credit: "ArnoldReinhold · Wikimedia Commons · CC BY-SA 3.0" },
  "dict": { file: "media/dict.jpg", title: "图书馆目录卡片柜 · 键值查找的现实隐喻", credit: "Grings1 · Wikimedia Commons · CC BY-SA 4.0" },
  "stack-queue": { file: "media/stack-queue.jpg", title: "早期主机操作台 · 任务排队与调用栈的历史现场", credit: "Unknown authorUnknown author · Wikimedia Commons · CC BY 2.0" },
  "tree-intro": { file: "media/tree-intro.png", title: "二叉树结构示意 · 分层节点与分支", credit: "Derrick Coetzee · Wikimedia Commons · Public domain" },
  "graph-intro": { file: "media/graph-intro.jpg", title: "互联网拓扑图 · 节点与边的真实世界", credit: "The Opte Project · Wikimedia Commons · CC BY 2.5" },
  "function": { file: "media/function.jpg", title: "艾达·洛夫莱斯像 · 最早的「程序与子程序」思想", credit: "Alfred Edward Chalon · Wikimedia Commons · Public domain" },
  "recursion": { file: "media/recursion.jpg", title: "套娃 · 递归「自己套自己」的直观隐喻", credit: "SUN JIAYI's · Wikimedia Commons · CC BY-SA 4.0" },
  "module-lib": { file: "media/module-lib.jpg", title: "吉多·范罗苏姆 · Python 与标准库生态", credit: "Doc Searls · Wikimedia Commons · CC BY-SA 2.0" },
  "exception": { file: "media/exception.jpg", title: "「Bug」词源实物 · 异常与错误处理的历史渊源", credit: "Courtesy of the Naval Surface Warfare Center, Dahlgren, VA., · Wikimedia Commons · Public domain" },
  "debugging": { file: "media/debugging.jpg", title: "格蕾丝·霍珀与 UNIVAC · 调试传统的标志人物", credit: "Unknown authorUnknown author · Wikimedia Commons · CC BY 2.0" },
  "complexity": { file: "media/complexity.jpg", title: "艾兹格·迪杰斯特拉 · 算法分析与结构化编程先驱", credit: "Hamilton Richards · Wikimedia Commons · CC BY-SA 3.0" },
  "linear-search": { file: "media/linear-search.jpg", title: "目录卡片柜 · 逐张比对的线性查找", credit: "Grings1 · Wikimedia Commons · CC BY-SA 4.0" },
  "binary-search": { file: "media/binary-search.jpg", title: "目录检索 · 有序数据对半查找的日常原型", credit: "Grings1 · Wikimedia Commons · CC BY-SA 4.0" },
  "bubble-sort": { file: "media/bubble-sort.jpg", title: "穿孔卡叠 · 早期机械排序的数据载体", credit: "ArnoldReinhold · Wikimedia Commons · CC BY-SA 3.0" },
  "selection-insertion-sort": { file: "media/selection-insertion-sort.jpg", title: "理扑克牌：插入排序的直觉来源", credit: "BlakeMagic · Wikimedia Commons · CC BY-SA 4.0" },
  "quick-merge-sort": { file: "media/quick-merge-sort.png", title: "归并排序示意 · 分治合并的经典结构", credit: "VineetKumar at English Wikipedia · Wikimedia Commons · Public domain" },
  "number-base": { file: "media/number-base.jpg", title: "二进制与算盘 · 数制的古今对照", credit: "David A. Aguilar (CfA) · Wikimedia Commons · CC0" },
  "graph-traversal": { file: "media/graph-traversal.jpg", title: "网络拓扑 · 图遍历的真实对象", credit: "The Opte Project · Wikimedia Commons · CC BY 2.5" },
  "backtracking": { file: "media/backtracking.jpg", title: "八皇后问题：回溯算法经典案例", credit: "Dietmar Rabich · Wikimedia Commons · CC BY-SA 4.0" },
  "shortest-path": { file: "media/shortest-path.jpg", title: "迪杰斯特拉 · 最短路径算法命名人", credit: "Hamilton Richards · Wikimedia Commons · CC BY-SA 3.0" },
  "mst": { file: "media/mst.png", title: "最小生成树示意 · 连通全图的最小代价", credit: "No machine-readable author provided. Dcoetzee assumed (based · Wikimedia Commons · Public domain" },
  "string-matching": { file: "media/string-matching.jpg", title: "Donald Knuth：KMP 算法的 K", credit: "Alex Handy · Wikimedia Commons · CC BY-SA 2.0" },
  "hash-table": { file: "media/hash-table.jpg", title: "卡片目录 · 哈希「按键直达」的现实类比", credit: "Grings1 · Wikimedia Commons · CC BY-SA 4.0" },
  "bst": { file: "media/bst.png", title: "二叉搜索树示意 · 有序分层查找", credit: "No machine-readable author provided. Dcoetzee assumed (based · Wikimedia Commons · Public domain" },
  "inheritance-polymorphism": { file: "media/inheritance-polymorphism.jpg", title: "Barbara Liskov：里氏替换原则提出者", credit: "Kenneth C. Zirkel · Wikimedia Commons · CC BY-SA 3.0" },
  "file-io": { file: "media/file-io.jpg", title: "拆开的硬盘 · 数据持久化的物理介质", credit: "No machine-readable author provided. Ed g2s assumed (based o · Wikimedia Commons · CC BY-SA 3.0" },
  "database": { file: "media/database.jpg", title: "霍尔瑞斯穿孔卡 · 大规模数据表与普查数据库渊源", credit: "Herman Hollerith · Wikimedia Commons · Public domain" },
  "web-basics": { file: "media/web-basics.jpg", title: "蒂姆·伯纳斯-李 · 万维网发明者", credit: "Silvio Tanaka · Wikimedia Commons · CC BY 2.0" },
  "data-analysis-py": { file: "media/data-analysis-py.jpg", title: "Python 之父与计算工具 · 从算盘到数据分析", credit: "Doc Searls · Wikimedia Commons · CC BY-SA 2.0" },
  "ai-ml-intro": { file: "media/ai-ml-intro.png", title: "人工神经网络示意 · 机器学习入门视觉", credit: "en:User:Cburnett · Wikimedia Commons · CC BY-SA 3.0" },
  "oop-class": { file: "media/oop-class.jpg", title: "Alan Kay：面向对象与 Smalltalk 之父", credit: "Marcin Wichary from San Francisco, U.S.A. · Wikimedia Commons · CC BY 2.0" },
  "greedy": { file: "media/greedy.png", title: "硬币找零：贪心策略的生活原型", credit: "Confocal_measurement_of_1-euro-star_3d.png: Dr. Schorsch EUR · Wikimedia Commons · CC BY-SA 3.0" },
  "dp-intro": { file: "media/dp-intro.jpg", title: "Richard Bellman：动态规划创立者", credit: "Abraham H. Haddad · Wikimedia Commons · CC BY-SA 3.0" },
  "design-patterns": { file: "media/design-patterns.jpg", title: "Erich Gamma：《设计模式》作者之一", credit: "Erich Berger · Wikimedia Commons · CC BY-SA 4.0" },
};
