// 编程知识体系 — 全骨架（以 Python 风格为主，思想跨语言通用）
// 用「依赖关系」组织，不分先后年级，只看知识依赖
// theme: basics（编程基础）| control（控制结构）| structure（数据结构）| paradigm（程序设计）| algorithm（算法）
// level: 在依赖图中的深度（用于星空自动布局）

window.CODE_THEMES = {
  basics:    { name: '编程基础',   short: '基础', color: '#3b82f6', soft: '#dbeafe', deep: '#1e40af' },
  control:   { name: '控制结构',   short: '控制', color: '#f97316', soft: '#ffedd5', deep: '#c2410c' },
  structure: { name: '数据结构',   short: '结构', color: '#10b981', soft: '#d1fae5', deep: '#065f46' },
  paradigm:  { name: '程序设计',   short: '设计', color: '#0d9488', soft: '#ccfbf1', deep: '#0f766e' },
  algorithm: { name: '算法',       short: '算法', color: '#8b5cf6', soft: '#ede9fe', deep: '#5b21b6' },
  application: { name: '应用·数据·智能', short: '应用', color: '#e11d48', soft: '#ffe4e6', deep: '#9f1239' },
};

window.CODE_NODES = [
  // ───── 编程基础 ─────
  { id:'variable-assign', name:'变量与赋值', theme:'basics', level:1, prereqs:[],
    concept:'用一个名字保存数据，以后可以反复使用和修改',
    explanation:'变量是程序里的「带名字的盒子」。赋值用等号 = ，左边写变量名、右边写值。变量可以被重新赋值，旧值就被覆盖。理解"变量是引用而不是值本身"是后续函数、对象等概念的基础。',
    example:'age = 14 把 14 装进 age；之后写 age = age + 1，age 就变成 15。变量名要见名知意：用 score 而不是 a。',
    connections:['data-types','operators','io-basic','function'] },
  { id:'data-types', name:'数据类型', theme:'basics', level:1, prereqs:[],
    concept:'整数、小数、字符串、布尔等不同种类的数据',
    explanation:'不同类型的数据可以做的事不一样：数能加减乘除，字符串能拼接、切片，布尔只有 True/False。在 Python 里类型是动态的，但仍要心里清楚每个变量是什么类型，避免"数字加字符串"这类错误。',
    example:'10 是整数 int，3.14 是浮点数 float，"hello" 是字符串 str，True 是布尔 bool。可用 type(x) 查看 x 的类型。',
    connections:['operators','string','list','error-types'] },
  { id:'io-basic', name:'输入与输出', theme:'basics', level:2, prereqs:['variable-assign'],
    concept:'用 input 从键盘读入数据、用 print 把结果显示到屏幕',
    explanation:'程序通过输入获取数据、通过输出展示结果——这是和用户对话的基本方式。注意 input 读到的永远是字符串，做数学运算前要用 int() 或 float() 转换类型。',
    example:'name = input("你叫什么？") 读一行；print("你好", name) 输出问候。age = int(input("年龄：")) 把输入转成整数。',
    connections:['operators'] },
  { id:'operators', name:'运算符与表达式', theme:'basics', level:2, prereqs:['data-types'],
    concept:'算术（+−*/）、比较（== != < >）、逻辑（and or not）等组合数据的符号',
    explanation:'运算符把数据组合成表达式，得到新值。优先级与数学类似，乘除先于加减，比较运算返回布尔值。除法有 / （得小数）和 // （取整）两种，取模 % 用来判断整除/奇偶。',
    example:'(3+4)*2 等于 14；7 // 2 等于 3，7 % 2 等于 1；5 > 3 and 2 < 4 等于 True。',
    connections:['boolean-cond','if-else'] },
  { id:'comments-style', name:'注释与代码风格', theme:'basics', level:1, prereqs:[],
    concept:'用 # 写说明、给变量起有意义的名字、保持缩进与排版整洁',
    explanation:'代码是写给人看的，机器只是顺带执行。好的注释解释"为什么这么做"，不重复"做了什么"。Python 用缩进表示代码块——同一层缩进必须一致，否则报错。',
    example:'# 计算总分\\nscore = math + english + chinese  # 注释解释做什么\\n好的命名：student_count 比 n 易懂。',
    connections:['debugging'] },
  { id:'string', name:'字符串', theme:'basics', level:3, prereqs:['data-types','operators'],
    concept:'用引号包起来的一串字符，可以拼接、切片、查找',
    explanation:'字符串是最常用的非数值数据。它「不可变」——任何修改都会创建新字符串。常用操作：长度 len()、切片 s[1:3]、拼接 +、格式化 f"{x}"、查找 in。掌握字符串就掌握了文本处理的入口。',
    example:'s = "Hello"；s[0] 是 "H"，s[1:3] 是 "el"，len(s) 是 5；"Hi " + name；f"成绩：{score}" 把变量插入文本。',
    connections:['list','linear-search'] },
  { id:'error-types', name:'常见错误类型', theme:'basics', level:2, prereqs:['variable-assign'],
    concept:'语法错误、运行时错误、逻辑错误三大类',
    explanation:'**语法错误**程序根本跑不起来（括号没配对、缩进错）；**运行时错误**跑到一半崩溃（除零、找不到的变量、类型不匹配）；**逻辑错误**最难发现——程序能跑，但结果是错的。读懂报错信息是初学者的第一关。',
    example:'SyntaxError: invalid syntax 是语法错；NameError: name "x" is not defined 是用了没定义的变量；输出与预期不符就是逻辑错。',
    connections:['exception','debugging'] },

  // ───── 控制结构 ─────
  { id:'boolean-cond', name:'布尔与条件判断', theme:'control', level:2, prereqs:['operators'],
    concept:'用 True/False 和比较、逻辑运算判断条件是否成立',
    explanation:'条件判断是程序"做选择"的前提。比较运算（< == >）返回布尔值；and、or、not 把多个条件组合成更复杂的判断。注意：== 是比较，= 是赋值，初学者最容易混。',
    example:'age = 15；is_teen = age >= 13 and age <= 19 → True；not (5 > 3) → False。',
    connections:['if-else','while-loop','for-loop'] },
  { id:'if-else', name:'if-else 分支', theme:'control', level:3, prereqs:['boolean-cond'],
    concept:'根据条件真假执行不同代码块',
    explanation:'if 后面的条件为真就执行它的代码块，否则走 else 或 elif（"否则如果"）。多个条件按顺序判断，第一个为真的就执行，其余都跳过。这是程序"做决定"的基本机制。',
    example:'if score >= 60:\\n    print("及格")\\nelif score >= 40:\\n    print("差点")\\nelse:\\n    print("加油")',
    connections:['nested-loop','recursion'] },
  { id:'while-loop', name:'while 循环', theme:'control', level:3, prereqs:['boolean-cond'],
    concept:'只要条件为真就反复执行循环体',
    explanation:'while 适合"次数不确定"的重复——只要条件成立就继续。务必让条件最终能变假，否则成为死循环。常和"累加器""计数器"一起用。',
    example:'i = 0\\nwhile i < 5:\\n    print(i)\\n    i = i + 1   # 别忘了让 i 增加，否则死循环',
    connections:['break-continue'] },
  { id:'for-loop', name:'for 循环', theme:'control', level:3, prereqs:['boolean-cond'],
    concept:'对序列中的每个元素依次执行循环体',
    explanation:'for 用于"已知次数"或"遍历集合"。range(n) 生成 0..n-1，常用来重复 n 次；也可以直接遍历列表、字符串、字典。它比 while 更不容易写错。',
    example:'for i in range(5):\\n    print(i)  # 输出 0 1 2 3 4\\nfor ch in "Hi":\\n    print(ch)  # 输出 H i',
    connections:['nested-loop','break-continue','linear-search','complexity'] },
  { id:'nested-loop', name:'嵌套循环', theme:'control', level:4, prereqs:['for-loop'],
    concept:'循环体里再写一个循环，外循环每走一步，内循环完整跑一遍',
    explanation:'嵌套循环常用来处理二维数据（矩阵、表格、打印图形）和"两两组合"问题。注意：嵌套层数越多，运行次数是乘法关系，复杂度上升很快。',
    example:'for i in range(3):\\n    for j in range(3):\\n        print(i, j)  # 9 行输出，覆盖所有 (i,j) 组合',
    connections:['bubble-sort','complexity'] },
  { id:'break-continue', name:'break 与 continue', theme:'control', level:4, prereqs:['while-loop','for-loop'],
    concept:'break 立刻跳出当前循环；continue 跳过本轮、进入下一轮',
    explanation:'用 break 提前结束循环（如找到目标后不再继续找）；用 continue 跳过这一轮（如遇到坏数据时跳过它）。它们只影响最近一层的循环，嵌套时要注意。',
    example:'for x in nums:\\n    if x < 0:\\n        continue   # 跳过负数\\n    if x == 0:\\n        break      # 遇到 0 停止',
    connections:['linear-search'] },

  // ───── 数据结构 ─────
  { id:'list', name:'列表', theme:'structure', level:3, prereqs:['data-types'],
    concept:'有序、可修改的元素序列，用方括号表示',
    explanation:'列表是最常用的数据结构。元素按位置存放，下标从 0 开始；可以增删改查、可以装任何类型。掌握 append/索引/切片/len 是入门必备。',
    example:'scores = [85, 92, 78]；scores[0] 是 85；scores.append(100) 在末尾加；scores[1] = 95 改第 2 个。',
    connections:['dict','set-type','stack-queue','linked-list','linear-search','bubble-sort'] },
  { id:'dict', name:'字典', theme:'structure', level:4, prereqs:['list'],
    concept:'键-值对的集合，用键快速查到对应的值',
    explanation:'字典就像"现实中的电话本"——给一个名字（键）找一个号码（值）。查、改、加都是 O(1) 平均时间，非常快。键必须唯一且不可变；常用于统计、分组、配置。',
    example:'student = {"name": "小明", "age": 14, "score": 92}；student["age"] 取出 14；student["score"] = 95 改分数。',
    connections:['graph-intro'] },
  { id:'set-type', name:'集合', theme:'structure', level:4, prereqs:['list'],
    concept:'无序、不重复的元素集合',
    explanation:'集合自动去重、检查"在不在"也是平均 O(1)。常用于去重、判断重复、求交集/并集/差集。代价是元素没有顺序、不能用下标。',
    example:'s = {1, 2, 2, 3, 3, 3} 实际只存 {1, 2, 3}；3 in s → True；{1,2,3} & {2,3,4} → {2, 3}。',
    connections:[] },
  { id:'stack-queue', name:'栈与队列', theme:'structure', level:5, prereqs:['list'],
    concept:'栈是"后进先出"（LIFO），队列是"先进先出"（FIFO）',
    explanation:'栈像盘子摞起来，只能从顶端取；队列像排队买票，先来先服务。它们都是抽象模型——用列表就能模拟。栈用于函数调用、撤销、括号匹配；队列用于任务调度、广度优先搜索。',
    example:'栈：stack.append(x) 入栈，stack.pop() 出栈（取最后一个）。\\n队列：queue.append(x) 入队，queue.pop(0) 出队（取最早的）。',
    connections:['recursion'] },
  { id:'linked-list', name:'链表', theme:'structure', level:5, prereqs:['list'],
    concept:'每个节点存数据 + 指向下一个节点的引用',
    explanation:'链表的元素散落在内存里，靠"指针"串起来。在中间插入/删除很快（不用搬数据），但随机访问慢（要从头找）。它是理解树、图等更复杂结构的入门。',
    example:'节点 = (数据=5, 下一个→) → (数据=3, 下一个→) → (数据=8, 下一个→None)。要找第 3 个，必须从头数过去。',
    connections:['tree-intro'] },
  { id:'tree-intro', name:'树', theme:'structure', level:6, prereqs:['linked-list'],
    concept:'像家谱一样的分层结构：每个节点有 0 个或多个子节点',
    explanation:'树有唯一的根、没有环。常见的二叉树每个节点最多 2 个子。树用于文件系统、家谱、表达式解析、二分搜索树等。遍历方式包括前序、中序、后序、层序。',
    example:'文件夹结构就是树：根目录下若干子目录，每个子目录又有自己的子目录或文件。',
    connections:['graph-intro','recursion'] },
  { id:'graph-intro', name:'图', theme:'structure', level:6, prereqs:['tree-intro','dict'],
    concept:'节点 + 边的集合，可以有环，是树的更一般形式',
    explanation:'图能描述很多东西：朋友关系、地图、互联网。常用字典存"邻接表"：键是节点，值是它的邻居列表。理解图为后面的搜索算法（DFS、BFS、最短路）打基础。',
    example:'好友关系：{"小明": ["小红", "小华"], "小红": ["小明"], ...}。从一个人出发能找到所有他认识/认识的认识。',
    connections:[] },

  // ───── 程序设计 ─────
  { id:'function', name:'函数', theme:'paradigm', level:3, prereqs:['variable-assign'],
    concept:'把一段可重复使用的代码打包起来，用名字调用',
    explanation:'函数是程序的"乐高积木"——避免重复代码、让逻辑清晰。用 def 定义、用名字 + 括号调用。一个函数最好只做一件事，做完得有清楚的"结果"或"效果"。',
    example:'def add(a, b):\\n    return a + b\\nadd(2, 3) 返回 5。重复使用同一段加法逻辑，不必每次都重写。',
    connections:['params-return','scope','recursion','module-lib','oop-class'] },
  { id:'params-return', name:'参数与返回值', theme:'paradigm', level:4, prereqs:['function'],
    concept:'参数是函数的"输入"，return 是函数的"输出"',
    explanation:'参数让函数能处理不同输入；返回值让调用者拿到结果。Python 支持默认参数、关键字参数、可变参数（*args, **kwargs），灵活但要节制使用，保持函数接口简单。',
    example:'def greet(name, greeting="你好"):  # greeting 有默认值\\n    return f"{greeting}, {name}"\\ngreet("小明") → "你好, 小明"；greet("Tom", "Hi") → "Hi, Tom"。',
    connections:['oop-class'] },
  { id:'scope', name:'作用域', theme:'paradigm', level:4, prereqs:['function'],
    concept:'变量"在哪里可见"——局部、全局、内置',
    explanation:'函数内定义的变量是"局部的"，外面看不到、函数结束就消失。函数能读外面的全局变量但不能直接修改它（需用 global 声明）。理解作用域可以避免"为什么我的变量没生效"。',
    example:'x = 10  # 全局\\ndef f():\\n    x = 20  # 这是新的局部 x，不影响外面\\n    print(x)  # 20\\nf(); print(x)  # 还是 10',
    connections:[] },
  { id:'recursion', name:'递归', theme:'paradigm', level:5, prereqs:['function','if-else'],
    concept:'函数在自己内部再调用自己',
    explanation:'递归用"自己解决一个小问题"的方式解决大问题。**必须有终止条件（基础情形）**，否则会无限递归直到爆栈。它是树、图、分治算法的核心思想。',
    example:'def factorial(n):\\n    if n <= 1: return 1   # 基础情形\\n    return n * factorial(n - 1)   # 自己调用自己\\nfactorial(5) = 5×4×3×2×1 = 120。',
    connections:['binary-search','quick-merge-sort','dp-intro'] },
  { id:'module-lib', name:'模块与库', theme:'paradigm', level:4, prereqs:['function'],
    concept:'用 import 把别人写好的代码拿来用',
    explanation:'不必所有功能从零写——Python 有强大的标准库（math, random, datetime…）和海量第三方库（numpy, pandas, requests…）。学会"用现成的轮子"是工程能力的重要一面。',
    example:'import math\\nmath.sqrt(16) → 4.0；math.pi → 3.14...\\nimport random\\nrandom.randint(1, 6) 模拟掷骰子。',
    connections:[] },
  { id:'oop-class', name:'面向对象（类与对象）', theme:'paradigm', level:5, prereqs:['function','params-return'],
    concept:'用「类」定义一种"东西"的属性和行为，用对象表示具体的实例',
    explanation:'面向对象把"数据"和"操作数据的函数"绑在一起。类是模板（如"狗"），对象是具体的（如"我家的小白"）。它带来了封装、继承、多态这些组织大程序的强力工具。',
    example:'class Dog:\\n    def __init__(self, name):\\n        self.name = name\\n    def bark(self): return f"{self.name} 汪汪！"\\nDog("小白").bark() → "小白 汪汪！"',
    connections:[] },
  { id:'exception', name:'异常处理', theme:'paradigm', level:4, prereqs:['error-types','function'],
    concept:'用 try / except 接住运行时错误，避免程序崩溃',
    explanation:'有些错误防不胜防（用户乱输入、网络中断、文件不存在）。用 try 把可能出错的代码包起来，用 except 处理对应类型的异常。原则：只处理你知道怎么应对的异常，别用 except 吞掉所有错误。',
    example:'try:\\n    n = int(input("输入一个数："))\\nexcept ValueError:\\n    print("不是合法的数字！")  # 输入字母时不会崩，给个友好提示',
    connections:['debugging'] },
  { id:'debugging', name:'调试方法', theme:'paradigm', level:3, prereqs:['error-types'],
    concept:'用 print、断点、查看变量值等手段找出 bug',
    explanation:'调试是程序员的核心能力。最基础的方式是"打印调试"：在关键处 print 变量值，看是否符合预期。更高级用 IDE 断点单步、看调用栈。每修一个 bug 都问一句"我假设了什么没成立"。',
    example:'# 算总和算错了，先打印中间变量\\nfor x in nums:\\n    total += x\\n    print("加完", x, "后 total =", total)  # 哪一步开始错就清楚了',
    connections:[] },

  // ───── 算法 ─────
  { id:'complexity', name:'时间复杂度（大 O）', theme:'algorithm', level:4, prereqs:['for-loop'],
    concept:'用 O(...) 描述算法运行时间随数据规模增长的趋势',
    explanation:'两台同样性能的电脑跑同一个程序时间差不多，但程序 A 100 万数据 1 秒、程序 B 要 1 小时——差距来自算法的"增长趋势"。O(1) 常数、O(log n) 二分、O(n) 一遍、O(n²) 双层循环、O(2ⁿ) 暴搜。',
    example:'for x in nums: print(x)  → O(n)\\nfor i in nums:\\n    for j in nums:\\n        print(i, j)  → O(n²)',
    connections:['linear-search','binary-search','bubble-sort','greedy','dp-intro'] },
  { id:'linear-search', name:'线性查找', theme:'algorithm', level:4, prereqs:['for-loop','list'],
    concept:'从头到尾依次比较，直到找到目标或走完',
    explanation:'最直白的查找方法，对未排序数据是唯一选择。最坏 O(n)。优化也很有限，主要适用于数据规模小或数据无序的情况。',
    example:'def find(nums, target):\\n    for i, x in enumerate(nums):\\n        if x == target: return i\\n    return -1',
    connections:['binary-search'] },
  { id:'binary-search', name:'二分查找', theme:'algorithm', level:5, prereqs:['list','recursion'],
    concept:'每次把搜索范围对半砍——前提是数据已排序',
    explanation:'查电话簿不会一页一页翻，会先翻到中间。二分查找正是这种思路，O(log n) 时间。前提：数据必须有序。每次比较中间元素：相等就找到、小了往右、大了往左。',
    example:'在 [1,3,5,7,9,11] 里找 7：先看中间 5，目标更大→看右半 [7,9,11]；中间 9，目标更小→看左半 [7]；找到，返回下标。',
    connections:[] },
  { id:'bubble-sort', name:'冒泡排序', theme:'algorithm', level:4, prereqs:['nested-loop','list'],
    concept:'反复比较相邻两个，逆序就交换，让大的"冒"到后面',
    explanation:'最容易理解的排序算法。每轮把最大的元素"冒"到最后；n 个元素跑 n-1 轮即可。时间 O(n²)，效率不高，但思路清晰，适合做入门。',
    example:'[5, 3, 8, 1] 第一轮：(5,3)交换→3,5,8,1；(5,8)不换；(8,1)交换→3,5,1,8。继续两轮，结果 [1,3,5,8]。',
    connections:['selection-insertion-sort','quick-merge-sort'] },
  { id:'selection-insertion-sort', name:'选择排序与插入排序', theme:'algorithm', level:5, prereqs:['bubble-sort'],
    concept:'选择：每轮选出最小放到最前；插入：把每个元素插到前面已排好的合适位置',
    explanation:'两种和冒泡同级（O(n²)）但思路不同的排序。**插入排序**对"几乎有序"的数据非常快，是很多语言内置排序的小数据优化分支。理解它们也帮你看懂高级排序的思路。',
    example:'插入排序 [5,3,8,1]：取 3 插到 5 前→[3,5,8,1]；取 8 在 5 后→[3,5,8,1]；取 1 插到最前→[1,3,5,8]。',
    connections:[] },
  { id:'quick-merge-sort', name:'快速排序与归并排序', theme:'algorithm', level:7, prereqs:['recursion','selection-insertion-sort'],
    concept:'分治思想：把大问题拆成小问题，分别解决再合起来',
    explanation:'**快排**：选一个基准，比它小的放左、大的放右，左右递归排好。**归并**：先把数组对半拆到只剩 1 个，再两两合并成有序序列。两者平均都是 O(n log n)，是工业级排序的主流方案。',
    example:'快排：[5,3,8,1,4] 以 5 为基准 → 左 [3,1,4]、右 [8]，递归排左 → [1,3,4]，最终 [1,3,4,5,8]。',
    connections:[] },
  { id:'greedy', name:'贪心算法', theme:'algorithm', level:6, prereqs:['complexity','if-else'],
    concept:'每一步都选当前看起来最好的——简单但不一定能得全局最优',
    explanation:'贪心适合具有"局部最优 → 全局最优"性质的问题，如找零钱、活动选择、最小生成树。它不像动态规划那样穷举所有路径，因此非常快，但用错时机会得到次优解。',
    example:'找零 25 元：贪心先用 20，再用 5，得 2 张；总比一张一张试快得多。但货币体系不规则时贪心可能不是最优。',
    connections:[] },
  { id:'dp-intro', name:'动态规划入门', theme:'algorithm', level:7, prereqs:['recursion','complexity'],
    concept:'把大问题分解为重复子问题，用一张表保存答案避免重复计算',
    explanation:'纯递归（如计算斐波那契）会重复算很多遍同一个子问题——动态规划把每个子问题的答案记下来下次直接查表。它是算法竞赛、最优化问题的核心方法之一，也是面试常考。',
    example:'斐波那契 fib(n) = fib(n-1) + fib(n-2)，纯递归 O(2ⁿ)；记忆化后变 O(n)：建一张表，第一次算完就存，下次直接读。',
    connections:['dp-advanced'] },

  // ───── 高中·进阶：基础与编码 ─────
  { id:'number-base', name:'进制与数据编码', theme:'basics', level:2, prereqs:['data-types'],
    concept:'数据在计算机里以二进制存储，可在二/八/十/十六进制间转换，字符也按编码表存为数字',
    explanation:'计算机底层只有 0 和 1，所以一切数据都要编码成二进制。理解进制转换、位的概念，才能看懂内存、颜色值（#FF0000）、位运算和数据溢出。陷阱：浮点数用二进制近似表示，所以 0.1+0.2 不等于 0.3，比较小数别用 == 。',
    example:'十进制 13 = 二进制 1101 = 十六进制 D。字符 "A" 的 ASCII 是 65。Python：bin(13) → "0b1101"，ord("A") → 65，hex(255) → "0xff"。',
    connections:['hash-table','complexity-advanced'] },

  // ───── 高中·进阶：算法分析与设计 ─────
  { id:'complexity-advanced', name:'算法复杂度分析进阶', theme:'algorithm', level:5, prereqs:['complexity'],
    concept:'区分时间/空间复杂度，分析最好/最坏/平均情形，理解均摊复杂度与递归复杂度',
    explanation:'入门只看"双层循环是 O(n²)"，进阶要会分析递归式、空间开销、以及"平均很快但偶尔很慢"的均摊情况。信息学竞赛里"能不能在 1 秒内跑完"全靠这一步估算。陷阱：别只盯时间——递归占用的栈空间、开的辅助数组都是空间成本。',
    example:'二分查找时间 $O(\\log n)$、空间 $O(1)$；归并排序时间 $O(n\\log n)$、空间 $O(n)$。动态数组 append 单次最坏 $O(n)$，但均摊 $O(1)$。',
    connections:['divide-conquer','dp-advanced'] },
  { id:'divide-conquer', name:'分治算法', theme:'algorithm', level:8, prereqs:['recursion','quick-merge-sort'],
    concept:'把问题分成若干同类的子问题，递归解决再合并结果——分、治、合三步',
    explanation:'分治是快排、归并背后的统一思想：当一个问题能拆成规模更小的同类问题时就用它。会用主定理（Master Theorem）估复杂度。陷阱：子问题必须相互独立、且合并代价不能太大，否则分治反而变慢。',
    example:'归并排序：把数组对半拆到只剩一个，再两两合并。递归式 $T(n)=2T(n/2)+O(n)$，解得 $O(n\\log n)$。求最大子数组、快速幂也是分治。',
    connections:['shortest-path','mst'] },
  { id:'graph-traversal', name:'图的遍历（BFS/DFS）', theme:'algorithm', level:7, prereqs:['graph-intro','recursion'],
    concept:'系统地访问图中每个节点：BFS 一层层向外扩、DFS 沿一条路走到底再回退',
    explanation:'BFS 用队列、按距离由近到远访问，天然求"无权图最短步数"；DFS 用递归或栈、能走多深走多深，适合连通性、找路径、拓扑排序。陷阱：图可能有环，必须用 visited 集合标记已访问，否则会无限循环。',
    example:'迷宫找最短路用 BFS（队列）；判断两点是否连通、找出所有连通块用 DFS。社交网络"几度好友"就是 BFS 的层数。',
    connections:['shortest-path','mst','backtracking'] },
  { id:'backtracking', name:'回溯算法', theme:'algorithm', level:6, prereqs:['recursion'],
    concept:'用递归尝试每种选择，走不通就"撤销"上一步、退回去换一条路',
    explanation:'回溯是"带剪枝的暴力搜索"：系统地枚举所有可能，但在发现当前部分解不可行时立即回退，省掉大量无用尝试。是 N 皇后、数独、全排列、组合问题的通用框架。陷阱：撤销选择（恢复现场）一定要和做选择成对出现，否则状态会污染。',
    example:'全排列 [1,2,3]：选 1→选 2→选 3 得 [1,2,3]，回退换 3,2 …。N 皇后：逐行放皇后，冲突就回退换列。',
    connections:['dp-advanced'] },
  { id:'dp-advanced', name:'动态规划进阶', theme:'algorithm', level:8, prereqs:['dp-intro'],
    concept:'掌握经典 DP 模型：背包、最长公共子序列、区间 DP、状态压缩等',
    explanation:'入门的 DP 只是"记忆化斐波那契"，进阶要会自己定义状态、写状态转移方程、确定计算顺序。关键三问：状态是什么、怎么从小状态推出大状态、边界如何初始化。陷阱：状态定义不准会导致转移方程根本写不出来——先想清楚 dp[i] 到底代表什么。',
    example:'0/1 背包：dp[i][w] = 前 i 件物品、容量 w 时的最大价值，转移 $dp[i][w]=\\max(dp[i-1][w],\\ dp[i-1][w-w_i]+v_i)$。最长公共子序列、编辑距离同理。',
    connections:['ai-ml-intro'] },
  { id:'shortest-path', name:'最短路径算法', theme:'algorithm', level:8, prereqs:['graph-traversal'],
    concept:'在带权图中求两点间代价最小的路径，如 Dijkstra、Floyd 算法',
    explanation:'BFS 只能解无权图最短路，带权图要用 Dijkstra（单源、非负权，配优先队列加速）或 Floyd（多源、能处理负权但慢）。这是地图导航、网络路由的核心。陷阱：Dijkstra 不能处理负权边，遇到负权要换 Bellman-Ford。',
    example:'地图从 A 到 B 最快路线 = 把路口当节点、路程当边权，跑 Dijkstra。Floyd 三重循环求任意两点最短路，时间 $O(n^3)$。',
    connections:['mst'] },
  { id:'mst', name:'最小生成树', theme:'algorithm', level:8, prereqs:['graph-traversal','union-find'],
    concept:'用最小的总边权把图中所有节点连成一棵树，如 Kruskal、Prim 算法',
    explanation:'要把若干城市用最短的总线路连通，就是最小生成树问题。Kruskal 把边从小到大加入、用并查集判断是否成环；Prim 从一个点不断长出最近的边。是贪心 + 并查集的经典应用。陷阱：Kruskal 每加一条边都要判环，否则会形成回路而不是树。',
    example:'通信网络铺光缆：n 个基站、若干可选线路各有造价，求连通所有基站的最低总造价。Kruskal：边排序后逐条尝试，不成环就选。',
    connections:[] },
  { id:'string-matching', name:'字符串匹配算法', theme:'algorithm', level:4, prereqs:['string'],
    concept:'在长文本中高效查找一个模式串出现的位置，如 KMP 算法',
    explanation:'朴素匹配每次失配都回退重来，最坏 $O(nm)$。KMP 用预处理的"前缀函数"记住已匹配信息、失配时不回退主串，做到 $O(n+m)$。这是搜索、文本编辑、生物信息（DNA 比对）的基础。陷阱：理解难点在 next/前缀数组的含义——它表示"最长的相同前后缀长度"。',
    example:'在 "ababcababa" 中找 "ababa"：朴素法多次回退；KMP 利用模式串内部重复，失配时跳到正确位置，不重头再来。',
    connections:[] },

  // ───── 高中·进阶：数据结构 ─────
  { id:'hash-table', name:'哈希表', theme:'structure', level:5, prereqs:['dict'],
    concept:'用哈希函数把键映射到数组下标，实现平均 O(1) 的查找/插入',
    explanation:'字典之所以快，底层就是哈希表。哈希函数把任意键算成一个数组位置；不同键算到同一位置叫"冲突"，用链地址法或开放寻址解决。理解它才明白"为什么字典查找几乎是瞬间的"。陷阱：哈希分布不均或表太满时会大量冲突，最坏退化到 $O(n)$。',
    example:'存 {"小明":92}：hash("小明") % 表长 = 下标，把值放进去。查的时候同样算一次下标直接取，不用逐个比较。',
    connections:['database'] },
  { id:'heap', name:'堆与优先队列', theme:'structure', level:7, prereqs:['tree-intro'],
    concept:'一种特殊的完全二叉树，根永远是最大（或最小）值，用来快速取极值',
    explanation:'普通队列先进先出，优先队列"最重要的先出"，底层用堆实现。堆能在 $O(\\log n)$ 内插入和取出极值，是堆排序、Dijkstra、Top-K 问题的引擎。陷阱：堆只保证"根是极值"，不是整体有序，别指望遍历它就能得到排序结果。',
    example:'小顶堆取最小值：根就是最小，取走后把末尾元素放到根再"下沉"调整。Python 用 heapq：heappush、heappop。求"实时第 K 大"常用堆。',
    connections:['shortest-path'] },
  { id:'bst', name:'二叉搜索树', theme:'structure', level:7, prereqs:['tree-intro'],
    concept:'左子树都比根小、右子树都比根大的二叉树，让查找像二分一样快',
    explanation:'BST 把二分查找的思想搬到树上：查找、插入、删除平均都是 $O(\\log n)$，且能保持元素有序（中序遍历即升序）。陷阱：如果按已排好序的数据依次插入，树会退化成一条链、复杂度变 $O(n)$——这正是 AVL、红黑树等"平衡树"要解决的问题。',
    example:'插入 5,3,8,1：5 为根，3 比 5 小放左，8 比 5 大放右，1 比 3 小放 3 的左。查 8：根 5→右→找到，只比较两次。',
    connections:[] },
  { id:'union-find', name:'并查集', theme:'structure', level:7, prereqs:['tree-intro'],
    concept:'专门维护"谁和谁在同一组"的数据结构，支持快速合并和查询',
    explanation:'用一个数组记录每个元素的"父亲"，同一棵树的元素就属于同一集合。配合"路径压缩"和"按秩合并"两个优化，单次操作几乎是 $O(1)$。是求连通分量、判环、最小生成树的利器。陷阱：忘了路径压缩，查询会沿链一路向上、退化变慢。',
    example:'判断朋友圈：find(a)==find(b) 说明 a、b 已在同一圈；交了新朋友就 union(a,b) 把两圈合并。Kruskal 用它判断加边是否成环。',
    connections:['mst'] },

  // ───── 高中·进阶：程序设计与工程 ─────
  { id:'inheritance-polymorphism', name:'继承与多态', theme:'paradigm', level:6, prereqs:['oop-class'],
    concept:'子类继承父类的属性与方法并可扩展；同一个调用对不同对象表现出不同行为',
    explanation:'继承让"狗""猫"复用"动物"的共性、只写各自不同的部分，避免重复代码。多态让你对一组不同对象用统一接口（都调 .speak()），运行时自动选对应实现。陷阱：别滥用继承表达"有一个"的关系（组合往往更好），继承表达的是"是一种"。',
    example:'class Animal: def speak(self): ... ；class Dog(Animal): def speak(self): return "汪"；class Cat(Animal): def speak(self): return "喵"。for a in [Dog(),Cat()]: print(a.speak()) → 汪 喵。',
    connections:['design-patterns'] },
  { id:'design-patterns', name:'软件设计思想与设计模式', theme:'paradigm', level:7, prereqs:['oop-class','inheritance-polymorphism'],
    concept:'前人总结的、应对常见设计问题的可复用解决方案模板',
    explanation:'当程序变大，"怎么组织代码才好改、好扩展"比"能不能跑"更重要。设计模式（单例、工厂、观察者、策略等）和原则（高内聚低耦合、面向接口编程）是被验证过的经验。陷阱：模式是用来解决真实问题的，别为了用模式而把简单代码搞复杂——过度设计和不设计一样糟。',
    example:'观察者模式：被观察对象状态变化时自动通知所有订阅者（如界面数据变了刷新显示）。工厂模式：用一个函数统一创建对象，调用方不关心具体类。',
    connections:[] },

  // ───── 高中·进阶：应用·数据·智能 ─────
  { id:'file-io', name:'文件与数据持久化', theme:'application', level:4, prereqs:['string'],
    concept:'把数据读写到文件，让程序关闭后数据仍然保留',
    explanation:'变量在内存里，程序一关就没了；要长期保存就得写进文件。掌握文本文件读写、CSV/JSON 等常用格式，是处理真实数据的第一步。陷阱：打开文件后一定要关闭（用 with 自动管理），否则可能数据没写全或资源泄漏；还要注意编码（中文用 utf-8）。',
    example:'with open("data.txt", "w", encoding="utf-8") as f:\\n    f.write("成绩记录")\\n用 import json；json.dump(data, f) 把字典存成文件，json.load(f) 读回来。',
    connections:['database','data-analysis-py'] },
  { id:'database', name:'数据库与 SQL', theme:'application', level:5, prereqs:['dict','list'],
    concept:'用表格化的方式存储海量数据，用 SQL 语言增删改查',
    explanation:'当数据量大、关系复杂时，文件就不够用了，需要数据库。关系型数据库把数据存成"表"（行是记录、列是字段），用 SQL 高效查询。理解表、主键、查询，是做任何带数据的应用的基础。陷阱：没建索引的大表查询会很慢；多表关联要想清楚用哪个字段连接。',
    example:'SELECT name, score FROM students WHERE score >= 90 ORDER BY score DESC; 查出所有 90 分以上的学生姓名和分数并按分降序。',
    connections:['data-analysis-py','web-basics'] },
  { id:'web-basics', name:'网络与 Web 开发', theme:'application', level:5, prereqs:['function','module-lib'],
    concept:'浏览器与服务器通过 HTTP 请求/响应交换数据，构成网站和网络应用',
    explanation:'上网的本质是客户端（浏览器）发请求、服务器回响应。理解 HTTP 方法（GET/POST）、URL、前后端分工、API 接口，才能做网站、调用网络服务、写爬虫。陷阱：永远不要相信用户输入的数据，要在服务器端校验，否则有安全漏洞。',
    example:'import requests；r = requests.get("https://api.../weather?city=北京")；data = r.json()  # 拿到天气 JSON。前端发请求、后端查数据库再返回，就是一次完整交互。',
    connections:[] },
  { id:'data-analysis-py', name:'数据分析与可视化', theme:'application', level:5, prereqs:['list','dict'],
    concept:'用 Python 工具（pandas、matplotlib 等）清洗数据、统计分析、画成图表',
    explanation:'真实数据往往杂乱：缺失、重复、格式不一。数据分析就是"清洗→统计→可视化→得出结论"。pandas 像"代码版 Excel"处理表格，matplotlib 画图。这是科创项目里把实验数据变成结论的关键能力。陷阱：图表别误导人——坐标轴从 0 开始、选对图表类型，相关不等于因果。',
    example:'import pandas as pd；df = pd.read_csv("scores.csv")；df["score"].mean() 求平均；df.groupby("class").mean() 分班统计；再用 matplotlib 画柱状图直观展示。',
    connections:['ai-ml-intro'] },
  { id:'ai-ml-intro', name:'人工智能与机器学习初步', theme:'application', level:9, prereqs:['dp-advanced','data-analysis-py'],
    concept:'让计算机从数据中"学习"规律、自动做预测或分类，而不是靠人写死规则',
    explanation:'传统程序是人写规则；机器学习是给大量"输入-答案"样本，让模型自己找规律。基本流程：准备数据→训练模型→评估→预测。理解监督学习（有标签）/无监督（无标签）、训练集/测试集、过拟合，是看懂 AI 的入门。陷阱：用训练数据评估等于作弊——必须用没见过的测试集；模型把训练集背得太死（过拟合）在新数据上反而差。',
    example:'根据房屋面积预测房价（回归）、根据邮件内容判断是否垃圾邮件（分类）。把数据分 80% 训练、20% 测试，训练后在测试集上看准确率是否过关。',
    connections:[] },
];

// 推导：边集合（由 prereqs 自动生成）
window.CODE_EDGES = window.CODE_NODES.flatMap(n =>
  (n.prereqs || []).map(p => ({ from: p, to: n.id }))
);

// 节点查询
window.CODE_NODE_BY_ID = Object.fromEntries(window.CODE_NODES.map(n => [n.id, n]));

// 每条边的「教学理由」——为什么先学 A 才能学 B（自动生成中性表述）
function edgeReason(fromId, toId) {
  const from = window.CODE_NODE_BY_ID[fromId];
  const to = window.CODE_NODE_BY_ID[toId];
  if (!from || !to) return '';
  const cross = from.theme === to.theme ? '' : '跨主题地';
  return `${from.name}提供了${to.name}所需的概念、语法或工具基础，先理解它，才能${cross}把${to.name}里的代码、结构和算法说清楚。`;
}

window.CODE_EDGE_WHY = Object.fromEntries(
  window.CODE_EDGES.map(e => [`${e.from}→${e.to}`, edgeReason(e.from, e.to)])
);

// 难度档（入门/进阶/高阶）：复用 NODE_GRADE / GRADE_RANK 的接口，但语义改成难度
window.CODE_NODE_GRADE = {
  // 入门（level 1-2，新手能直接上手）
  'variable-assign':'入门','data-types':'入门','io-basic':'入门','operators':'入门','comments-style':'入门','error-types':'入门',
  'boolean-cond':'入门',
  // 进阶（level 3-5，有循环、函数后能驾驭）
  'string':'进阶','if-else':'进阶','while-loop':'进阶','for-loop':'进阶','nested-loop':'进阶','break-continue':'进阶',
  'list':'进阶','dict':'进阶','set-type':'进阶','stack-queue':'进阶','linked-list':'进阶',
  'function':'进阶','params-return':'进阶','scope':'进阶','recursion':'进阶','module-lib':'进阶','oop-class':'进阶','exception':'进阶','debugging':'进阶',
  'complexity':'进阶','linear-search':'进阶','binary-search':'进阶','bubble-sort':'进阶','selection-insertion-sort':'进阶',
  // 高阶（level 6-7，思想/工程性更深）
  'tree-intro':'高阶','graph-intro':'高阶','quick-merge-sort':'高阶','greedy':'高阶','dp-intro':'高阶',
  // 高一（进制编码、复杂度进阶、分治、图遍历、继承多态、文件、哈希表）
  'number-base':'高一','complexity-advanced':'高一','divide-conquer':'高一','graph-traversal':'高一',
  'inheritance-polymorphism':'高一','file-io':'高一','hash-table':'高一',
  // 高二（堆、BST、并查集、回溯、DP进阶、最短路、最小生成树、字符串匹配、数据库、Web、数据分析）
  'heap':'高二','bst':'高二','union-find':'高二','backtracking':'高二','dp-advanced':'高二',
  'shortest-path':'高二','mst':'高二','string-matching':'高二','database':'高二','web-basics':'高二','data-analysis-py':'高二',
  // 高三（设计模式、AI/机器学习）
  'design-patterns':'高三','ai-ml-intro':'高三',
};
window.CODE_GRADE_RANK = { '入门':1, '进阶':2, '高阶':3, '高一':4, '高二':5, '高三':6 };
